name: pypmi-docs

on: 
  workflow_dispatch:
  push:
      branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_page:
    if: github.repository_owner == 'netneurolab'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Install pypmi
        run: |
          pip install .
      - name: Build the docs
        run: |
          cd docs && make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: 'docs/_build/html'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4